apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-gateway
spec:
  selector:
    matchLabels:
      app: grpc-gateway
  template:
    metadata:
      labels:
        app: grpc-gateway
    spec:
      containers:
        - name: grpc-gateway
          image: butterv/kubernetes-sample1:0.0.12
