apiVersion: v1
kind: Service
metadata:
  name: grpc-gateway-active
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 10000
      nodePort: 30001
  selector:
    app: grpc-gateway
---
apiVersion: v1
kind: Service
metadata:
  name: grpc-gateway-preview
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 10000
      nodePort: 30002
  selector:
    app: grpc-gateway
